---
development:
  cloud_name: brazelton
  api_key: '276561819441672'
  api_secret: "-jb6L3ckAlTLrWwfjQmQOs1hNQA"
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: brazelton
  api_key: '276561819441672'
  api_secret: "-jb6L3ckAlTLrWwfjQmQOs1hNQA"
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: brazelton
  api_key: '276561819441672'
  api_secret: "-jb6L3ckAlTLrWwfjQmQOs1hNQA"
  enhance_image_tag: true
  static_image_support: false
